metrics:
  metricsPath: "/monitoring/prometheus/metrics"
  # Whether to add model name and version as prometheus labels
  modelLabels: false

modelProvider:
  type: diskProvider
  diskProvider:
    baseDir: "./model_repo"

modelCache:
  hostModelPath: "./models"
  size: 30000

serving:
  servingModelPath: "/models"
  grpcHost: "localhost:8500"
  restHost: "http://localhost:8501"
  maxConcurrentModels: 2
  grpcConfigTimeout: 10 # timeout in seconds
  grpcPredictTimeout: 60
  metricsPath: "/monitoring/prometheus/metrics"

proxy:
  replicasPerModel: 3
  grpcTimeout: 10

serviceDiscovery:
  type: etcd
  heartbeatTTL: 5
  etcd:
    serviceName: tfservingcache
    endpoints: ["localhost:2379"]
    allowLocalhost: true
    authorization:
      username: root
      password: foobar
